# https://hub.docker.com/r/itsthenetwork/nfs-server-alpine/

version: '3'
services:
  nfs:
    image: itsthenetwork/nfs-server-alpine:latest
    privileged: true
    volumes:
      - ./shared:/shared
    environment:
      - SHARED_DIRECTORY=/shared
      - READ_ONLY=true
      - SYNC=true
      - PERMITTED=10.11.12.*
    ports:
      - 2049:2049