version: '3'
services:
  shellinabox:
    image: sspreitzer/shellinabox:latest
    container_name: shellinabox
    restart: always
    ports:
      - 4200:4200
    environment:
      - SIAB_PASSWORD=qwert
      - SIAB_SUDO=true
      - SIAB_USER=docker
